databases: []

services:
  - type: web
    name: ppp3-tracker
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: START_DATE
        value: "2026-01-24"
